FROM alpine:latest

RUN <<EOT
set -eux
apk add --update --no-cache tzdata envsubst
adduser -h /home/container -D container
EOT

USER container
ENV USER=container HOME=/home/container

WORKDIR /home/container
COPY ./entrypoint.sh /
CMD ["/bin/ash", "/entrypoint.sh"]
