FROM debian:bullseye-slim

RUN <<EOT
set -eux
apt-get update -y
apt-get install -y ca-certificates curl git jq wget
useradd -d /home/container -m container
EOT

USER container
ENV USER=container HOME=/home/container

WORKDIR /home/container
COPY ./entrypoint.sh /
CMD ["/bin/bash", "/entrypoint.sh"]
