name: _step.image

on:
  workflow_call:
    inputs:
      dockerfile_path:
        type: string
        required: true
      docker_build_context:
        type: string
        required: true
      build_args:
        type: string
        required: true
      push:
        type: boolean
        required: true
      image_name:
        type: string
        required: true
      image_tag_maker_script:
        type: string
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: config
        uses: actions/github-script@v7
        with:
          script: ${{ inputs.image_tag_maker_script }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}
          tags: ${{ steps.config.outputs.target_tags }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ${{ inputs.dockerfile_path }}
          context: ${{ inputs.docker_build_context }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
