name: Docker images for Minecraft runtime yolks

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/image_minecraft_runtime.yml"
      - "yolks/minecraft/runtime/**"
  schedule:
    - cron: '0 6 * * 0'  # At 06:00 on Sunday

jobs:
  image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        system: ['jammy', 'bullseye', 'slim-bullseye']
        java: ['8', '11', '17', '21']
        mcdr: ['latest', '2.12', '2.11', '2.10']

    steps:
      - uses: actions/checkout@v3

      - name: Generate image config
        id: config
        run: |
          echo "image_tag=minecraft-runtime-${{ matrix.system }}-${{ matrix.java }}-${{ matrix.mcdr }}" >> $GITHUB_OUTPUT
          
          if [ ${{ matrix.mcdr }} == 'latest' ]; then
            echo "mcdr_req=mcdreforged" >> $GITHUB_OUTPUT
          else
            echo "mcdr_req=mcdreforged~=${{ matrix.mcdr }}" >> $GITHUB_OUTPUT
          fi
          
          if [ ${{ matrix.system }} == 'jammy' ]; then
            echo "image_base=eclipse-temurin" >> $GITHUB_OUTPUT
          elif [ ${{ matrix.system }} == 'bullseye' ] || [ ${{ matrix.system }} == 'slim-bullseye' ]; then
            echo "image_base=openjdk" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
          
          if [ ${{ matrix.system }} == 'jammy' ] && [ ${{ matrix.mcdr }} == 'latest' ]; then
            echo "image_tag_extra=minecraft-runtime-${{ matrix.java }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fallenbreath/pterodactyl-yolks
          tags: |
            ${{ steps.config.outputs.image_tag }}
            ${{ steps.config.outputs.image_tag_extra }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: yolks/minecraft/runtime/Dockerfile
          context: yolks/minecraft/runtime
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            IMAGE_BASE=${{ steps.config.outputs.image_base }}
            SYSTEM=${{ matrix.system }}
            JAVA_VERSION=${{ matrix.java }}
            MCDR_REQUIREMENT=${{ steps.config.outputs.mcdr_req }}
