name: CI for Minecraft runtime yolks

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/image_minecraft_runtime.yml"
      - ".github/workflows/image_one.yml"
      - "yolks/minecraft/runtime/**"
  schedule:
    - cron: '0 7 1 * *'  # At 07:00 on day-of-month 1
  workflow_dispatch:

jobs:
  image:
    name: java=${{ matrix.java }}, mcdr=${{ matrix.mcdr }}
    strategy:
      matrix:
        java: ['8', '11', '17', '21']
        mcdr: ['latest', '2.14']

    uses: ./.github/workflows/image_one.yml
    secrets: inherit
    with:
      dockerfile_path: yolks/minecraft/runtime/Dockerfile
      docker_build_context: yolks/minecraft/runtime
      build_args: |-
        MCDR_VERSION=${{ matrix.mcdr }}
        JAVA_VERSION=${{ matrix.java }}
      image_name: fallenbreath/pterodactyl-yolks
      image_tag_maker_script: |-
        let targetTags = ['minecraft-runtime-${{ matrix.java }}-${{ matrix.mcdr }}']
        if ('${{ matrix.mcdr }}' == 'latest') {
          targetTags.push('minecraft-runtime-${{ matrix.java }}')
        }
        core.setOutput('target_tags', targetTags.join('\n'))
      push: ${{ github.event_name != 'pull_request' }}
